
# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------

spring:
  rabbitmq:
    host: "192.168.80.131"
    port: 5672
    username: "admin"
    password: "admin"
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations:
          - "./_x"